name: Publish tigotell-client

on:
  release:
    types: [published]

permissions:
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi
    if: startsWith(github.event.release.tag_name, 'client-v')
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Build package
        run: |
          python -m pip install build
          python -m build tigotell_client
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: tigotell_client/dist/
